### ISSUE TITLE
mseed crate handles timing conversion incorrectly

### ISSUE THREAD

**Issue by BIBIN-EUGINE** [damb/mseed#10]
The api `pack_raw()` does a wrong conversion of time for `starttime`. Inside `pack_raw()` it calls `util::time_to_nstime()` which is expected to return a unix timestamp in nano secs, but it returns seconds instead. Due to this wrong conversion of time miniseed record always provides invalid start time.

Fix: `util::time_to_nstime()` should call `unix_timestamp_nanos()`  instead `unix_timestamp()`.

**Comment by damb** [comment]
Thank you for reporting.

Though, the proposed fix doesn't work [`unix_timestamp_nanos()`](https://docs.rs/time/latest/time/struct.OffsetDateTime.html#method.unix_timestamp_nanos) returns an `i128`, while libmseed defines the `nstime_t` as `i64`.

One solution which comes to my mind (and should work) is using libmseed's [`ms_time2nstime()`](https://earthscope.github.io/libmseed/group__time-related.html#gaccd7c7b149cb4f969159b97c48e520f7) function. I'm going to fix this once I fully understand the details.

**Comment by BIBIN-EUGINE** [comment]
> Thank you for reporting.
> 
> Though, the proposed fix doesn't work [`unix_timestamp_nanos()`](https://docs.rs/time/latest/time/struct.OffsetDateTime.html#method.unix_timestamp_nanos) returns an `i128`, while libmseed defines the `nstime_t` as `i64`.
> 
> One of solution which comes to my mind (and should work) is using libmseed's [`ms_time2nstime()`](https://earthscope.github.io/libmseed/group__time-related.html#gaccd7c7b149cb4f969159b97c48e520f7) function. I'm going to fix this once I fully understand the details.

I have seen that internally it casted into i128, I would say casting to i64  would be good enough.

**Comment by damb** [comment]
I'd rather leave it up to libmseed whether casting is *good enough* or not.

**Comment by damb** [comment]
Does e114b82a8ca1745519109fcfe24a71cf52fe7bd4 solve this issue on your side?

**Comment by BIBIN-EUGINE** [comment]
> Does [e114b82](https://github.com/damb/mseed/commit/e114b82a8ca1745519109fcfe24a71cf52fe7bd4) solve this issue on your side?

I have tried it for host system and it works as expected, whereas the cross compliation fails

ERROR
```
error[E0308]: `?` operator has incompatible types
   --> src/record.rs:286:39
    |
286 |         unsafe { util::nstime_to_time(check_nst(raw::msr3_endtime(self.0) as _)?) }
    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `i64`
    |
    = note: `?` operator cannot convert from `i64` to `i32`
help: you can convert an `i64` to an `i32` and panic if the converted value doesn't fit
    |
286 |         unsafe { util::nstime_to_time(check_nst(raw::msr3_endtime(self.0) as _)?.try_into().unwrap()) }
    |                                                                                 ++++++++++++++++++++

```

**Comment by damb** [comment]
Thank you.

933c27e8d948dddcd85c6398ee691a87c9659dcb should fix the time related compilation issue on ARM.

Do you mind checking once more?

**Comment by BIBIN-EUGINE** [comment]
> Thank you.
> 
> [933c27e](https://github.com/damb/mseed/commit/933c27e8d948dddcd85c6398ee691a87c9659dcb) should fix the time related compilation issue on ARM.
> 
> Do you mind checking once more?Thank you.


Yeah, I have verified for both host and ARM,  and also the examples.

**Comment by damb** [comment]
Great. Thanks again.

**Comment by BIBIN-EUGINE** [comment]
> Great. Thanks again.

Thanks @damb for the quick fix..much appreciated:)
