### ISSUE TITLE
Sample rate is not being used by miniseed record

### ISSUE THREAD

**Issue by BIBIN-EUGINE** [damb/mseed#11]
The sample rate is not being set inside the `pack_raw` method and therefore the miniseed records produces `0hz` as sample rate in all case.

In addition to that, it would be  nice if we can provide `sample_rate_factor` and `sample_rate_multipler` as paramters to `pack_raw` method instead of `sample rate` to give more control to the user  rather than miniseed crate decode these values from sample rate.

**Comment by damb** [comment]
Thanks a lot. Does d1b73f20ec7e22a87f238cd12281864266c16c1a fix the issue on your side?

**Comment by damb** [comment]
> In addition to that, it would be nice if we can provide `sample_rate_factor` and `sample_rate_multipler` as paramters to `pack_raw` method instead of `sample rate` to give more control to the user rather than miniseed crate decode these values from sample rate.

Let's continue this discussion within #12.

**Comment by BIBIN-EUGINE** [comment]
> 

Thanks @damb , this change fix the issue.
