### ISSUE TITLE
Feature to create miniseed record with encoded data samples

### ISSUE THREAD

**Issue by BIBIN-EUGINE** [damb/mseed#13]
**New feature request:**

Currently, the mseed crate only support to create miniseed records with raw data samples (i.e, not encoded). It would be good to create a function which can take encoded data samples as input and create a miniseed record.

**Comment by damb** [comment]
If I understand you correctly, you'd like to have facilities which allow packing miniSEED records from encoded data samples. Is this correct?

EDIT: How would handle the *number of samples* attribute of the record? Of course, we could pass the number of samples as an additional parameter to the pack function, however, this would be sensible only when packing into a miniSEED `v3` record.

**Comment by BIBIN-EUGINE** [comment]
Hi @damb , I didn't understand why it's only possible/sensible in the case of miniSEED `v3` record.

Assume we have the encoded data and num. of smaples, 

-   call `msr3_pack_header2`  to get the miniseed header for `v2`
-  then put together encoded data and miniseed header  to create miniseed record.

Moreover, I am thinking it would be make more sense if we have this functionality in libmseed and mseed crate can provide a wrapper around that function. What do you think?

**Comment by damb** [comment]
Sorry for not being clear enough. Packing encoded data and providing the number of samples is only sensible into a miniSEED `v3` record because `v3` records are of variable length. On the other hand, miniSEED `v2` records are of fixed size. Suppose the encoded data doesn't fit into a miniSEED `v2` record. How would you perform splitting the encoded data samples?

**Comment by BIBIN-EUGINE** [comment]
Good point, my suggestion is that this feature creates only a single record (size of rec len = header + encode data < MAX_REC_LEN) and if the encoded data doesn't fit in a single record supported by v2 then send a error message back to caller and let the caller handles that case.

**Comment by damb** [comment]
Does your suggestion work for all `mseed::MSDataEncoding`s if padding missing samples with zeroes? I'm not familiar with all the encodings libmseed provides.

As you already suggested, I'd rather prefer an implementation of libmseed. Let's ping @chad-earthscope and ask him what he thinks about this idea.

**Comment by damb** [comment]
Closed due to inactivity. Please, feel free to reopen if required.

**Comment by chad-earthscope** [comment]
The use case appears quite esoteric.  Can a real-world use case be described?

Not only would the library (libmseed or this crate) need to blindly trust the encoded payload and number of samples, the end result would likely end up with unfilled v2 records with a lot of padding.  It is for these reasons that libmseed includes a [msr3_repack_mseed3()](https://earthscope.github.io/libmseed/group__miniseed-record.html#ga2bcbc4dab5da941a83dac8494f56d06b), but no v2 equivalent.
