### ISSUE TITLE
Cross compliation failure for libmseed-sys crate

### ISSUE THREAD

**Issue by BIBIN-EUGINE** [damb/mseed#5]
Hi @damb , I have been looking at this mseed crate for miniseed support in one of our applications. The issue on which I am stumbled upon is with the cross compliation. 

I can build the mseed crate successfully for the native, whereas the cross complaition is always fails to generate bindings.
Here is the error log:

```
running: "arm-linux-gnueabi-ar" "s" "/usr/src/my-workspace/target/armv5te-unknown-linux-gnueabi/debug/build/libmseed-sys-078e0e0ff4ad9e48/out/libmseed.a"
  exit status: 0
  cargo:rustc-link-lib=static=mseed
  cargo:rustc-link-search=native=/usr/src/my-workspace/target/armv5te-unknown-linux-gnueabi/debug/build/libmseed-sys-078e0e0ff4ad9e48/out
  cargo:rustc-link-lib=static=mseed
  cargo:rustc-link-search=native=/cargo/registry/src/index.crates.io-6f17d22bba15001f/libmseed-sys-0.2.1+3.0.17/vendor
  cargo:rerun-if-changed=/cargo/registry/src/index.crates.io-6f17d22bba15001f/libmseed-sys-0.2.1+3.0.17/vendor/libmseed.h
  Searching for libraries at: /cargo/registry/src/index.crates.io-6f17d22bba15001f/libmseed-sys-0.2.1+3.0.17/vendor
  Generate bindings.rs
  cargo:rerun-if-env-changed=TARGET
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_armv5te-unknown-linux-gnueabi
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_armv5te_unknown_linux_gnueabi
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
  

  --- stderr
  /usr/include/stdlib.h:25:10: fatal error: 'bits/libc-header-start.h' file not found
  thread 'main' panicked at 'Unable to generate bindings: ClangDiagnostic("/usr/include/stdlib.h:25:10: fatal error: 'bits/libc-header-start.h' file not found\n")', /cargo/registry/src/index.crates.io-6f17d22bba15001f/libmseed-sys-0.2.1+3.0.17/build.rs:82:10
 ```

The error seems like is not able to find `bits/libc-header-start.h` in the host search path, but those files are exisitng for target as well as for native at below paths.

`/usr/include/x86_64-linux-gnu/bits/libc-header-start.h
/usr/arm-linux-gnueabi/include/bits/libc-header-start.h`

Build Enviroment (local)
OS: ubuntu 22.04
rustup: 1.71.1

Build Enviroment (docker)
OS: debian bullseye
rustup: 1.71.1

Is the mseed crate only supports native build? Could you please provide some insights into the above issue. Many Thanks

**Comment by damb** [comment]
Interesting. I never have cross-compiled the crate before. However, the issue is related to cross-compiling the `libmseed-sys` crate. The libmseed C sources are compiled by means of the [cc](https://crates.io/crates/cc) crate while the raw bindings are created with the [bindgen](https://crates.io/crates/bindgen) crate. See also the [`build.rs`](https://github.com/damb/mseed/blob/6d8d3e033cb7c4bcf041ee05c14e2919219de9ca/libmseed-sys/build.rs) of the `libmseed-sys` crate.

According to the [bindgen documentation](https://rust-lang.github.io/rust-bindgen/faq.html#how-to-generate-bindings-for-a-custom-target), bindgen should be able to build for a custom target.

**Comment by damb** [comment]
BTW, did you notice the difference in the paths?:

- `/usr/include/x86_64-linux-gnu/bits/libc-header-start.h`
-  `/usr/arm-linux-gnueabi/include/bits/libc-header-start.h`

I.e. the second path doesn't start with `/usr/include/...`. Apparently clang can't find the location of the C standard library for your target platform. Is there a way to point clang to the correct location?

**Comment by BIBIN-EUGINE** [comment]
Good point..I have checked the [bindgen documentation](https://rust-lang.github.io/rust-bindgen/faq.html#how-to-generate-bindings-for-a-custom-target) for custom target and it says if we are using it as library then we should specify the target for the builder. 
So i guess, do we need to mention `builder.clang_arg("--target=XXX")` in here: https://github.com/damb/mseed/blob/main/libmseed-sys/build.rs#L63

**Comment by damb** [comment]
Well, instead of changing the existing configuration I rather would go with the approach described at https://github.com/rust-lang/rust-bindgen/issues/1229#issuecomment-707950665. Could you give this a try?

When it comes to the correct include path a symlink located under `/usr/include/` pointing to `/usr/arm-linux-gnueabi/` might do it as well.

See also https://doc.rust-lang.org/cargo/reference/config.html#target for additional details.

**Comment by BIBIN-EUGINE** [comment]
Yeah, I have tried above mentioned apprach and it's compling for the target (at least there is no dependency issue), but I am getting  complier error from libmseed crate for cross compliation.

```
error[E0308]: mismatched types
  --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/mseed-0.4.1/src/record.rs:86:12
   |
86 |     Text = raw::DE_TEXT as c_char,
   |            ^^^^^^^^^^^^^^^^^^^^^^ expected `i8`, found `u8`

error[E0308]: mismatched types
  --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/mseed-0.4.1/src/record.rs:88:17
   |
88 |     Integer16 = raw::DE_INT16 as c_char,
   |                 ^^^^^^^^^^^^^^^^^^^^^^^ expected `i8`, found `u8`

error[E0308]: mismatched types
  --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/mseed-0.4.1/src/record.rs:90:17
   |
90 |     Integer32 = raw::DE_INT32 as c_char,
   |                 ^^^^^^^^^^^^^^^^^^^^^^^ expected `i8`, found `u8`

error[E0308]: mismatched types
  --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/mseed-0.4.1/src/record.rs:92:15
   |
92 |     Float32 = raw::DE_FLOAT32 as c_char,
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i8`, found `u8`

error[E0308]: mismatched types
  --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/mseed-0.4.1/src/record.rs:94:15
   |
94 |     Float64 = raw::DE_FLOAT64 as c_char,
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i8`, found `u8`

error[E0308]: mismatched types
  --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/mseed-0.4.1/src/record.rs:96:14
   |
96 |     Steim1 = raw::DE_STEIM1 as c_char,
   |              ^^^^^^^^^^^^^^^^^^^^^^^^ expected `i8`, found `u8`

error[E0308]: mismatched types
  --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/mseed-0.4.1/src/record.rs:98:14
   |
98 |     Steim2 = raw::DE_STEIM2 as c_char,
   |              ^^^^^^^^^^^^^^^^^^^^^^^^ expected `i8`, found `u8`

error[E0308]: mismatched types
   --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/mseed-0.4.1/src/record.rs:100:18
    |
100 |     GeoScope24 = raw::DE_GEOSCOPE24 as c_char,
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i8`, found `u8`

error[E0308]: mismatched types
   --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/mseed-0.4.1/src/record.rs:102:19
    |
102 |     GeoScope163 = raw::DE_GEOSCOPE163 as c_char,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i8`, found `u8`

error[E0308]: mismatched types
   --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/mseed-0.4.1/src/record.rs:104:19
    |
104 |     GeoScope164 = raw::DE_GEOSCOPE164 as c_char,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i8`, found `u8`

error[E0308]: mismatched types
   --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/mseed-0.4.1/src/record.rs:106:12
    |
106 |     CDSN = raw::DE_CDSN as c_char,
    |            ^^^^^^^^^^^^^^^^^^^^^^ expected `i8`, found `u8`

error[E0308]: mismatched types
   --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/mseed-0.4.1/src/record.rs:108:11
    |
108 |     SRO = raw::DE_SRO as c_char,
    |           ^^^^^^^^^^^^^^^^^^^^^ expected `i8`, found `u8`

error[E0308]: mismatched types
   --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/mseed-0.4.1/src/record.rs:110:14
    |
110 |     DWWSSN = raw::DE_DWWSSN as c_char,
    |              ^^^^^^^^^^^^^^^^^^^^^^^^ expected `i8`, found `u8`
    ```

**Comment by damb** [comment]
Ok. One issue solved.

The issue you described is related to the fact that the C standard doesn't force whether a `char` is `signed` or `unsigned` by default (see https://stackoverflow.com/questions/2054939/is-char-signed-or-unsigned-by-default). Apparently on `arm` `char` is `unsigned` while on `x86_64` it is `signed`. This definitely requires a fix.

Do you want to provide a PR fixing the issue?

**Comment by BIBIN-EUGINE** [comment]
Yeah sure, I am glad to work on this issue. Thanks @damb

**Comment by damb** [comment]
Perfect. Let's proceed the discussion at #6.
